### ISSUE TITLE
Can't load logs

### ISSUE THREAD

**Issue by BannableBurres** [vyneer/orvods-go#12]
Hi, so im not sure if this is a well known issue or not because i thought it was possibly just linked to Overrustlelogs being down the first day i tried to use the site. But its been doing it for the third day in a row now, making me unable to load the chat at all. Basically making the site useless for me. 

![LOADING](https://user-images.githubusercontent.com/69073165/89120428-8b094b80-d4b6-11ea-9226-531359574efd.PNG)

**Comment by Rollinrolan** [comment]
Same here, glad to see it wasn't just me

**Comment by vyneer** [comment]
Hi there!

I checked OverRustleLogs and there are logs missing starting from 2020-07-31 19:58:42 UTC and ending at 2020-08-01 22:42:16 UTC, which is why chat doesn't work for [696545233](https://vyneer.me/?id=696545233) and the first ~2 hours of [697530382](https://vyneer.me/?id=697530382), everything else should be okay.

I added a log fallback button in the chat settings so that you can use my logs instead of ORL, let me know if it works.

If the button doesn't appear for you, Shift-Left Click the refresh button to force refresh the cache.

![image](https://user-images.githubusercontent.com/41237021/89122177-f01c6b80-d4cd-11ea-8e05-45c698f68964.png)

**Comment by BannableBurres** [comment]
Aah, yeah i figured it was an issue on overrustlelogs, a shame that it went on for so long, but at least its back now thank god. 
...And now I understand how the log fallback works.. I didnt know you had to click on the "use" bar lmao. Maybe it could use a different sort of visualization? Honestly just thought the grey bar was a title bar...

**Comment by vyneer** [comment]
Yeah, sorry, my ui/ux stuff is pretty shitty. I'll make it more button-y.

Closing the issue since it's been resolved.
