### ISSUE TITLE
Possible quality options for slower internet speeds?

### ISSUE THREAD

**Issue by PenguinDogg** [vyneer/orvods-go#17]
I'm not sure if it's possible, or if you'd have to use another player, but it would be a good idea to have different quality options for those with slower internet.

**Comment by vyneer** [comment]
I'm gonna guess that you're talking about the "vodstiny" tab (because YouTube and Twitch have quality options in their players), in which case, no, I can't, because I don't run [vodstiny](https://polecat.me/vodstiny), Polecat does, I just embed his data.

It even says so on when you open the tab MMMM
![vodstiny notice](https://user-images.githubusercontent.com/41237021/167981164-657078e2-dced-46a1-a49a-a8400c1510d4.jpeg)
